### ISSUE TITLE
 Use lisp-case for function and variable names

### ISSUE THREAD

**Issue by olivergeorge** [netizer/relational_mapper#2]
It's more common for clojure libraries to use kebab-case instead of snake_case.

Perhaps worth renaming things early:
- swap relational_mapper for `relational-mapper`
- swap find_all for `find-all`

https://github.com/bbatsov/clojure-style-guide#lisp-case

**Comment by olivergeorge** [comment]
Oops, find_all is a typo in the README

**Comment by netizer** [comment]
:+1: 
done: https://github.com/netizer/relational_mapper/commit/042bb7f9c4d59b9b4277c0e56b76ca2374aa54b6
thanks :-)
